### ISSUE TITLE
Refactor multi modules

### ISSUE THREAD

**Issue by siyeonSon** [depromeet/street-drop-server#102]
## DESCRIPTION
- refactor to new architecture
<img width="704" alt="Screenshot 2023-06-17 at 6 11 47 PM" src="https://github.com/depromeet/street-drop-server/assets/87802191/075b81a2-7c68-4722-86a2-7ce0f53cd349">

### TODO
- [x] create streetdrop-common module
- [x] create streetdrop-domain module
- [x] move utils, validators to streetdrop-common module
- [x] move entity to streetdrop-domain module
- [x] move repository, service, security to streetdrop-api module
- [x] connect dependencies between modules

## TEST
no test required
