### ISSUE TITLE
Combine notification module and batch module

### ISSUE THREAD

**Issue by siyeonSon** [depromeet/street-drop-server#444]
### DESCRIPTION
- move notification module to batch module

### TODO
- [ ] Move notification service codes to batch module
- [ ] Move notification domain codes to domain module
- [ ] Change the new path of the FCM json file in .gitignore file

### TEST
do not need to test
