### ISSUE TITLE
[Notification] change mongodb -> mysql

### ISSUE THREAD

**Issue by siyeonSon** [depromeet/street-drop-server#455]
#### Stop using MongoDB
We chose MongoDB in that it is free for schema changes and has a high write speed.

However, there were many inconveniences when introducing a new database.
- I have to study about the new database.
- It is cumbersome to manage because user information is in RDB and user device information is in MongoDB.
- So far, I haven't felt the benefits of scalability and writing speed.

Therefore, **maintaining and managing MongoDB was an unreasonable attempt.** And it was unreasonable to handle a large number of specifications with a small number of people. So **it was sufficient to store notification information in the RDB.**

### TODO
- [x] change MongoRepository interface -> JpaRepository interface
- [x] remove mongodb dependency
- [x] manage notification domains with flyway
