### ISSUE TITLE
Add Test Code for Item Detail API

### ISSUE THREAD

**Issue by siyeonSon** [depromeet/street-drop-server#46]
## DESCRIPTION
Add Test Code for Item Detail API 

### TODO
- [x] ItemService test code
- [x] ItemController test code

## TEST
- [x] FindNearItems not exist
- [x] FindNearItems success
- [x] When invalid values ​​are entered
